# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44950b9aa4d09ccaecb7eef2751ef20678eede2d4b26b374142d86beef4044a99947616f262dd36f6464fc7fb2d1a0e1e4d24f4ec5b5038de2e53930005c7ccc

test:
  secret_key_base: 52eb81479fe11af100074656c047c2522e9fe42493370d87186de275bb3ed0890dc7553acec09079dba928ec4c4c0251f0490fcb7d70c0d1e160ccc567193768

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
